'use strict';
const express=require('express');const http=require('http');const path=require('path');const crypto=require('crypto');const{Server}=require('socket.io');const{createClient}=require('redis');const{createAdapter}=require('@socket.io/redis-adapter');
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:true,credentials:false},serveClient:true,transports:['polling','websocket']});
const PORT=Number(process.env.PORT)||3000,HOST='0.0.0.0',TTL=2592000,memoryRooms=new Map(),memoryProfiles=new Map(),timerHandles=new Map(),revealHandles=new Map();let redis=null,storageMode='memory';
const randomId=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():crypto.randomBytes(16).toString('hex');app.disable('x-powered-by');app.use(express.json({limit:'32kb'}));app.use(express.static(path.join(__dirname,'public')));const roomKey=c=>`deathbox:room:${c}`,profileKey=t=>`deathbox:profile:${t}`;
async function initRedis(){if(!process.env.REDIS_URL){console.warn('REDIS_URL not configured; using memory rooms.');return}const pub=createClient({url:process.env.REDIS_URL});pub.on('error',e=>console.error('Redis error:',e.message));await pub.connect();const sub=pub.duplicate();await sub.connect();io.adapter(createAdapter(pub,sub));redis=pub;storageMode='redis'}
async function getProfile(t){if(!t)return null;if(!redis)return memoryProfiles.get(t)||null;const v=await redis.get(profileKey(t));return v?JSON.parse(v):null}async function saveProfile(p){p.updatedAt=Date.now();if(!redis)memoryProfiles.set(p.token,p);else await redis.set(profileKey(p.token),JSON.stringify(p),{EX:TTL})}async function getRoom(c){if(!c)return null;if(!redis)return memoryRooms.get(c)||null;const v=await redis.get(roomKey(c));return v?JSON.parse(v):null}async function saveRoom(r){r.lastActive=Date.now();if(!redis)memoryRooms.set(r.code,r);else await redis.set(roomKey(r.code),JSON.stringify(r),{EX:TTL})}async function roomExists(c){return redis?Boolean(await redis.exists(roomKey(c))):memoryRooms.has(c)}async function roomCount(){if(!redis)return memoryRooms.size;let cursor='0',count=0;do{const x=await redis.scan(cursor,{MATCH:'deathbox:room:*',COUNT:100});cursor=String(x.cursor);count+=x.keys.length}while(cursor!=='0');return count}
app.get('/health',async(_q,res)=>{try{res.json({ok:true,storage:storageMode,rooms:await roomCount()})}catch(e){res.status(503).json({ok:false,error:e.message})}});app.get('*',(_q,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const suits=['♠','♥','♣','♦'],ranks=[['A',14],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10],['J',11],['Q',12],['K',13]];const makeDeck=()=>suits.flatMap(s=>ranks.map(([label,value])=>({suit:s,label,value,id:randomId()})));function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}const ALPH='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';async function makeCode(){for(let a=0;a<100;a++){const c=Array.from({length:5},()=>ALPH[crypto.randomInt(0,ALPH.length)]).join('');if(!(await roomExists(c)))return c}throw Error('No room code')}const norm=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,5),clean=v=>String(v||'').trim().replace(/\s+/g,' ').slice(0,20),playerFor=(r,s)=>r?.players.find(p=>p.id===s.data.playerId);
function newPlayer(name,socketId,profileToken=null){return{id:randomId(),socketId,profileToken,name,connected:true,guesses:0,correct:0,points:0,penalty:0,riskTotal:0,riskGuesses:0}}
function resetStats(r){r.players.forEach(p=>Object.assign(p,{guesses:0,correct:0,points:0,penalty:0,riskTotal:0,riskGuesses:0}))}
function startDeathbox(r){r.gameId=randomId();r.startedAt=Date.now();r.started=true;r.turn=0;r.streak=0;r.selected=null;r.deck=shuffle(makeDeck());r.piles=Array.from({length:9},()=>[r.deck.pop()]);r.phase='outside';r.outsideCorrect=0;r.logs=[];r.result=`${r.players[0].name} goes first.`;resetStats(r)}
function startLethal(r){r.gameId=randomId();r.startedAt=Date.now();r.started=true;r.turn=0;r.streak=0;r.selected=null;r.deck=shuffle(makeDeck());r.piles=[[],[],[],[],[]];for(const i of[0,1,2,3,4])r.piles[i].push(r.deck.pop());r.phase='outside';r.outsideCorrect=0;r.logs=[];r.result=`${r.players[0].name} starts. Get two outside guesses, then the center color.`;resetStats(r)}
function start(r){r.game==='lethalcross'?startLethal(r):startDeathbox(r)}
function phaseLabel(r){if(r.game!=='lethalcross')return'';if(r.phase==='outside')return `${r.outsideCorrect}/2 outside`;if(r.phase==='center')return'Center color';return'Bonus center streak'}
function pub(r){return{code:r.code,hostId:r.hostId,started:r.started,difficulty:r.difficulty,game:r.game,turn:r.turn,streak:r.streak,selected:r.selected,phase:r.phase,phaseLabel:phaseLabel(r),outsideCorrect:r.outsideCorrect||0,deckCount:r.deck.length,centerCount:r.game==='lethalcross'?(r.piles[2]?.length||0):0,piles:r.piles.map(p=>({count:p.length,top:p[p.length-1]||null})),players:r.players.map(p=>({id:p.id,name:p.name,connected:p.connected,guesses:p.guesses,correct:p.correct,points:p.points,penalty:p.penalty,riskTotal:p.riskTotal,riskGuesses:p.riskGuesses})),logs:r.logs.slice(0,120),result:r.result,timer:r.timer,reveal:r.reveal||null,currentPlayerId:r.players[r.turn]?.id||null}}
async function broadcast(r){await saveRoom(r);if(r.started||r.gameId)await snapshotRoom(r,r.started?'active':'completed');io.to(r.code).emit('roomState',pub(r))}async function socketRoom(s){return s.data.roomCode?getRoom(s.data.roomCode):null}function addLog(r,p,text,type='info'){r.logs.unshift({at:Date.now(),playerId:p?.id||null,player:p?.name||'',text,type})}function advance(r){r.turn=(r.turn+1)%r.players.length;r.streak=0;r.selected=null;r.phase='outside';r.outsideCorrect=0}function clearTimer(r){const h=timerHandles.get(r.code);if(h)clearInterval(h);timerHandles.delete(r.code);r.timer=null}
function chance(r,current,direction){if(!r.deck.length)return 0;return r.deck.filter(c=>direction==='higher'?c.value>current.value:c.value<current.value).length/r.deck.length}function riskPoints(x){return Math.max(1,Math.min(10,Math.round(1+(1-x)*9)))}function facePenalty(c){if(c.label==='A')return 11;if(['J','Q','K'].includes(c.label))return 10;return Number(c.label)}
function recycleLethal(r){const outside=[0,1,3,4],pool=[];for(const i of outside)pool.push(...r.piles[i]);r.deck=shuffle(pool);for(const i of outside)r.piles[i]=[r.deck.pop()];r.selected=null;r.result='Outside cards reshuffled. The center pile stays secured.'}
function ensureLethalDeck(r){if(r.deck.length)return true;if((r.piles[2]?.length||0)>=52){r.started=false;r.result='LethalCross complete — all 52 cards reached the center pile!';return false}recycleLethal(r);return r.deck.length>0}
function setPenalty(r,p,seconds,nextTurn,reason){p.penalty+=seconds;r.timer={playerId:p.id,target:seconds,elapsed:0,running:false,complete:false,nextTurn:Boolean(nextTurn),reason};r.streak=0;r.selected=null}
async function createRoom(host,s,difficulty,game){const code=await makeCode(),r={code,hostId:host.id,players:[host],difficulty:['easy','normal','hard'].includes(difficulty)?difficulty:'normal',game:game==='lethalcross'?'lethalcross':'deathbox',started:false,turn:0,streak:0,deck:[],piles:[],selected:null,phase:'outside',outsideCorrect:0,logs:[],result:'Waiting for the creator to start.',timer:null,lastActive:Date.now()};await saveRoom(r);await s.join(code);s.data.roomCode=code;s.data.playerId=host.id;return r}

function profileStats(p){const games=p.games||[];return games.reduce((a,g)=>{a.games++;a.guesses+=g.guesses||0;a.correct+=g.correct||0;a.penalty+=g.penalty||0;a.riskTotal+=g.riskTotal||0;a.riskGuesses+=g.riskGuesses||0;return a},{games:0,guesses:0,correct:0,penalty:0,riskTotal:0,riskGuesses:0})}
function profilePublic(p){return{token:p.token,name:p.name,activeRoomCode:p.activeRoomCode||null,games:(p.games||[]).slice(-30).reverse(),stats:profileStats(p)}}
async function upsertProfile(token,name){let p=await getProfile(token);if(!p)p={token:token||randomId(),name:clean(name),createdAt:Date.now(),games:[],activeRoomCode:null};if(name)p.name=clean(name)||p.name;await saveProfile(p);return p}
async function snapshotPlayer(r,pl,status='saved'){if(!pl?.profileToken)return;const pr=await getProfile(pl.profileToken);if(!pr)return;const rec={id:r.gameId||r.code,roomCode:r.code,game:r.game,status,startedAt:r.startedAt||Date.now(),savedAt:Date.now(),guesses:pl.guesses||0,correct:pl.correct||0,penalty:pl.penalty||0,riskTotal:pl.riskTotal||0,riskGuesses:pl.riskGuesses||0};const i=(pr.games||[]).findIndex(g=>g.id===rec.id);if(i>=0)pr.games[i]=rec;else(pr.games||(pr.games=[])).push(rec);pr.activeRoomCode=status==='active'?r.code:null;await saveProfile(pr)}
async function snapshotRoom(r,status='active'){for(const pl of r.players)await snapshotPlayer(r,pl,status)}

io.on('connection',s=>{
s.on('profileLogin',async({name,token}={})=>{try{const p=await upsertProfile(String(token||''),name);s.data.profileToken=p.token;s.emit('profileReady',profilePublic(p));if(p.activeRoomCode){const r=await getRoom(p.activeRoomCode);const pl=r?.players.find(x=>x.profileToken===p.token);if(r&&pl){pl.connected=true;pl.socketId=s.id;await s.join(r.code);s.data.roomCode=r.code;s.data.playerId=pl.id;s.emit('roomJoined',{playerId:pl.id,room:pub(r),resumed:true});await broadcast(r)}}}catch(e){s.emit('errorMessage','Could not open profile.')}});
s.on('createRoom',async({name,difficulty,game,profileToken}={})=>{try{const n=clean(name);if(!n)return s.emit('errorMessage','Enter your name.');const h=newPlayer(n,s.id,profileToken||s.data.profileToken),r=await createRoom(h,s,difficulty,game);s.emit('roomJoined',{playerId:h.id,room:pub(r)});await broadcast(r)}catch(e){console.error(e);s.emit('errorMessage','Could not create the room.')}});
s.on('joinRoom',async({name,code:raw,profileToken}={})=>{try{const n=clean(name),code=norm(raw);if(!n)return s.emit('errorMessage','Enter your name.');const r=await getRoom(code);if(!r)return s.emit('errorMessage','That access code is not active.');if(r.started)return s.emit('errorMessage','This game has already started.');const p=newPlayer(n,s.id,profileToken||s.data.profileToken);r.players.push(p);await s.join(code);s.data.roomCode=code;s.data.playerId=p.id;s.emit('roomJoined',{playerId:p.id,room:pub(r)});await broadcast(r)}catch(e){s.emit('errorMessage','Could not join the room.')}});
s.on('startGame',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r||p?.id!==r.hostId)return;s.start;start(r);await snapshotRoom(r,'active');await broadcast(r)});
s.on('selectPile',async index=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.started||!p||r.timer||r.reveal||r.players[r.turn]?.id!==p.id)return;const i=Number(index);if(!Number.isInteger(i)||!r.piles[i])return;if(r.game==='lethalcross'&&(r.phase!=='outside'||i===2))return;r.selected=i;await broadcast(r)});
s.on('choose',async direction=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.started||!p||r.timer||r.reveal||r.players[r.turn]?.id!==p.id||!['higher','lower'].includes(direction)||r.selected===null)return;if(!r.deck.length&&r.game==='lethalcross'&&!ensureLethalDeck(r)){await broadcast(r);return}if(!r.deck.length)return;const pile=r.piles[r.selected],cur=pile[pile.length-1],ch=chance(r,cur,direction),next=r.deck.pop();pile.push(next);const correct=direction==='higher'?next.value>cur.value:next.value<cur.value,aw=riskPoints(ch);p.guesses++;p.riskGuesses++;p.riskTotal+=aw;if(correct){p.correct++;r.streak++;r.outsideCorrect=(r.outsideCorrect||0)+1;r.result=`${p.name} got ${direction} right on ${next.label}${next.suit}. ${r.outsideCorrect}/2 outside guesses complete.`;addLog(r,p,r.result,'correct');r.selected=null;if(r.game==='lethalcross'&&r.outsideCorrect>=2){r.phase='center';r.result=`Two outside guesses complete. ${p.name} must now guess the center card color.`}else if(r.game!=='lethalcross'&&r.streak>=3){advance(r);r.result=`Turn complete. ${r.players[r.turn].name} is up.`}}else{const penalty=pile.length*(next.value===cur.value?2:1);r.result=`${p.name} missed. Drink for ${penalty} second${penalty===1?'':'s'} — the selected outside pile now has ${pile.length} cards.`;addLog(r,p,r.result,'wrong');r.reveal={playerId:p.id,card:next,message:r.result,penalty,nextTurn:false,reason:'outside',until:Date.now()+1800};r.phase='outside';r.outsideCorrect=0;setTimeout(async()=>{const x=await getRoom(r.code);if(!x?.reveal)return;const xp=x.players.find(z=>z.id===p.id);x.reveal=null;setPenalty(x,xp,penalty,false,'outside');await broadcast(x)},1800)}if(!r.deck.length&&r.game==='deathbox'){r.started=false;r.result='The deck is empty. Final results are ready.'}await broadcast(r)});
s.on('chooseColor',async color=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.started||r.game!=='lethalcross'||!p||r.timer||r.reveal||r.players[r.turn]?.id!==p.id||!['red','black'].includes(color)||r.phase==='outside')return;if(!ensureLethalDeck(r)){await broadcast(r);return}const next=r.deck.pop(),actual=['♥','♦'].includes(next.suit)?'red':'black';r.piles[2].push(next);p.guesses++;p.riskGuesses++;p.riskTotal+=5;const correct=color===actual;if(correct){p.correct++;r.streak++;r.result=`${p.name} called ${color.toUpperCase()} correctly: ${next.label}${next.suit}.`;addLog(r,p,r.result,'correct');if(r.phase==='center'){r.phase='bonus';r.result+=` All three required guesses are complete — keep calling colors to build the center pile.`}if((r.piles[2]?.length||0)>=52){r.started=false;r.result='LethalCross complete — all 52 cards reached the center pile!'}}else{const bonus=r.phase==='bonus';if(bonus){r.result=`${p.name} called ${color.toUpperCase()}, but ${next.label}${next.suit} was ${actual.toUpperCase()}. Bonus streak ended — no penalty.`;addLog(r,p,r.result,'wrong');advance(r);r.result+=` ${r.players[r.turn].name} is up.`}else{const penalty=facePenalty(next);r.result=`${p.name} called ${color.toUpperCase()}, but ${next.label}${next.suit} was ${actual.toUpperCase()}. Drink for ${penalty} second${penalty===1?'':'s'}.`;addLog(r,p,r.result,'wrong');r.reveal={playerId:p.id,card:next,message:r.result,penalty,nextTurn:false,reason:'center',until:Date.now()+1800};r.phase='outside';r.outsideCorrect=0;setTimeout(async()=>{const x=await getRoom(r.code);if(!x?.reveal)return;const xp=x.players.find(z=>z.id===p.id);x.reveal=null;setPenalty(x,xp,penalty,false,'center');await broadcast(x)},1800)}}await broadcast(r)});
s.on('startTimer',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.timer||r.timer.playerId!==p?.id||r.timer.running)return;r.timer.running=true;await broadcast(r);const h=setInterval(async()=>{const x=await getRoom(r.code);if(!x?.timer||!x.timer.running){clearInterval(h);timerHandles.delete(r.code);return}x.timer.elapsed++;if(x.timer.elapsed>=x.timer.target){x.timer.complete=true;x.timer.running=false;clearInterval(h);timerHandles.delete(r.code)}await broadcast(x)},1000);timerHandles.set(r.code,h)});
s.on('finishTimer',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.timer||r.timer.playerId!==p?.id||!r.timer.complete)return;const nextTurn=r.timer.nextTurn;clearTimer(r);if(nextTurn){advance(r);r.result=`Penalty complete. ${r.players[r.turn].name} is up.`}else{r.phase='outside';r.outsideCorrect=0;r.streak=0;r.selected=null;r.result=`Penalty complete. ${p.name} restarts the turn and needs two outside guesses again.`}await broadcast(r)});
s.on('getProfile',async()=>{const p=await getProfile(s.data.profileToken);if(p)s.emit('profileReady',profilePublic(p))});
s.on('newGame',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r||!p)return;await snapshotRoom(r,'archived');const pr=await getProfile(p.profileToken);if(pr){pr.activeRoomCode=null;await saveProfile(pr);s.emit('profileReady',profilePublic(pr))}s.leave(r.code);s.data.roomCode=null;s.data.playerId=null;s.emit('leftGame')});
s.on('restartGame',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(r&&p?.id===r.hostId){clearTimer(r);start(r);await broadcast(r)}});
s.on('disconnect',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(r&&p){p.connected=false;await broadcast(r)}})});
(async()=>{try{await initRedis();server.listen(PORT,HOST,()=>console.log(`Deathbox + LethalCross listening on ${PORT}`))}catch(e){console.error(e);process.exit(1)}})();
