'use strict';
const express=require('express');const http=require('http');const path=require('path');const crypto=require('crypto');const{Server}=require('socket.io');const{createClient}=require('redis');const{createAdapter}=require('@socket.io/redis-adapter');
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:true,credentials:false},serveClient:true,transports:['polling','websocket']});
const PORT=Number(process.env.PORT)||3000,HOST='0.0.0.0',TTL=2592000,memoryRooms=new Map(),memoryProfiles=new Map(),memoryUsernames=new Map(),timerHandles=new Map(),revealHandles=new Map();let redis=null,storageMode='memory';
const randomId=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():crypto.randomBytes(16).toString('hex');app.disable('x-powered-by');app.use(express.json({limit:'32kb'}));app.use(express.static(path.join(__dirname,'public')));const roomKey=c=>`deathbox:room:${c}`,profileKey=t=>`deathbox:profile:${t}`,usernameKey=u=>`deathbox:username:${u}`;
async function initRedis(){if(!process.env.REDIS_URL){console.warn('REDIS_URL not configured; using memory rooms.');return}const pub=createClient({url:process.env.REDIS_URL});pub.on('error',e=>console.error('Redis error:',e.message));await pub.connect();const sub=pub.duplicate();await sub.connect();io.adapter(createAdapter(pub,sub));redis=pub;storageMode='redis'}
async function getProfile(t){if(!t)return null;if(!redis)return memoryProfiles.get(t)||null;const v=await redis.get(profileKey(t));return v?JSON.parse(v):null}
async function getTokenByUsername(u){if(!u)return null;if(!redis)return memoryUsernames.get(u)||null;return await redis.get(usernameKey(u))}
async function getProfileByUsername(u){const t=await getTokenByUsername(u);return t?getProfile(t):null}
async function saveProfile(p){normalizeSocial(p);p.updatedAt=Date.now();if(!redis){memoryProfiles.set(p.token,p);if(p.username)memoryUsernames.set(p.username,p.token)}else{await redis.set(profileKey(p.token),JSON.stringify(p));if(p.username)await redis.set(usernameKey(p.username),p.token)}}
async function deleteProfile(t){if(!t)return;const p=await getProfile(t);if(!redis){memoryProfiles.delete(t);if(p?.username)memoryUsernames.delete(p.username)}else{const keys=[profileKey(t)];if(p?.username)keys.push(usernameKey(p.username));await redis.del(keys)}}async function getRoom(c){if(!c)return null;if(!redis)return memoryRooms.get(c)||null;const v=await redis.get(roomKey(c));return v?JSON.parse(v):null}async function saveRoom(r){r.lastActive=Date.now();if(!redis)memoryRooms.set(r.code,r);else await redis.set(roomKey(r.code),JSON.stringify(r),{EX:TTL})}async function deleteRoom(code){if(!redis)memoryRooms.delete(code);else await redis.del(roomKey(code))}async function roomExists(c){return redis?Boolean(await redis.exists(roomKey(c))):memoryRooms.has(c)}async function roomCount(){if(!redis)return memoryRooms.size;let cursor='0',count=0;do{const x=await redis.scan(cursor,{MATCH:'deathbox:room:*',COUNT:100});cursor=String(x.cursor);count+=x.keys.length}while(cursor!=='0');return count}
app.get('/health',async(_q,res)=>{try{res.json({ok:true,storage:storageMode,rooms:await roomCount()})}catch(e){res.status(503).json({ok:false,error:e.message})}});app.get('*',(_q,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const suits=['♠','♥','♣','♦'],ranks=[['A',14],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10],['J',11],['Q',12],['K',13]];const makeDeck=()=>suits.flatMap(s=>ranks.map(([label,value])=>({suit:s,label,value,id:randomId()})));function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}const ALPH='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';async function makeCode(){for(let a=0;a<100;a++){const c=Array.from({length:5},()=>ALPH[crypto.randomInt(0,ALPH.length)]).join('');if(!(await roomExists(c)))return c}throw Error('No room code')}const norm=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,5),clean=v=>String(v||'').trim().replace(/\s+/g,' ').slice(0,20),cleanUsername=v=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,18),validPasscode=v=>/^\d{6}$/.test(String(v||'')),hashPasscode=(code,salt=crypto.randomBytes(16).toString('hex'))=>({salt,hash:crypto.scryptSync(String(code),salt,32).toString('hex')}),verifyPasscode=(code,p)=>{try{return crypto.timingSafeEqual(Buffer.from(hashPasscode(code,p.passSalt).hash,'hex'),Buffer.from(p.passHash,'hex'))}catch{return false}},playerFor=(r,s)=>r?.players.find(p=>p.id===s.data.playerId);
function badgeForLevel(level){level=Math.max(1,Math.min(20,Number(level)||1));if(level>=20)return{color:'#f8e16c',tier:20};if(level>=15)return{color:'#d66bff',tier:15};if(level>=10)return{color:'#59b7ff',tier:10};if(level>=6)return{color:'#55e6a5',tier:6};return{color:'#b8bcc5',tier:1}}
function normalizeSocial(p){p.friends=Array.isArray(p.friends)?[...new Set(p.friends.map(cleanUsername).filter(Boolean))]:[];p.incomingRequests=Array.isArray(p.incomingRequests)?[...new Set(p.incomingRequests.map(cleanUsername).filter(Boolean))]:[];p.outgoingRequests=Array.isArray(p.outgoingRequests)?[...new Set(p.outgoingRequests.map(cleanUsername).filter(Boolean))]:[];return p}
const XP_MULTIPLIER={easy:1,normal:1.5,hard:2.25};
function xpNeededForLevel(level){if(level>=20)return 0;if(level<5)return 2000;if(level<10)return 5000;return 10000}
function xpProgress(total=0){let level=1,spent=0;total=Math.max(0,Math.floor(Number(total)||0));while(level<20){const need=xpNeededForLevel(level);if(total<spent+need)break;spent+=need;level++}const need=xpNeededForLevel(level),current=level>=20?0:total-spent;return{total,level,current,needed:need,remaining:level>=20?0:Math.max(0,need-current),percent:level>=20?100:Math.min(100,Math.round(current/need*100)),rank:level<=5?'Amateur':level<=10?'Pro':level<=15?'Veteran':'Hall of Fame'}}
async function awardXP(r,p,riskScore){const base=Math.max(10,Math.round((Number(riskScore)||1)*10)),earned=Math.round(base*(XP_MULTIPLIER[r.difficulty]||1));p.xpTotal=Math.max(0,Math.floor(Number(p.xpTotal)||0))+earned;p.xpEarned=(p.xpEarned||0)+earned;const before=xpProgress(p.xpTotal-earned),after=xpProgress(p.xpTotal);if(p.profileToken){const pr=await getProfile(p.profileToken);if(pr){pr.xpTotal=p.xpTotal;await saveProfile(pr);if(p.socketId)io.to(p.socketId).emit('profileReady',profilePublic(pr))}}return{earned,leveled:after.level>before.level,level:after.level,rank:after.rank}}
function newPlayer(name,socketId,profileToken=null,badgeColor=null,medals={easy:0,normal:0,hard:0},xpTotal=0){return{id:randomId(),socketId,profileToken,name,badgeColor:badgeForLevel(xpProgress(xpTotal).level).color,medals:{easy:medals.easy||0,normal:medals.normal||0,hard:medals.hard||0},xpTotal:Math.max(0,Math.floor(Number(xpTotal)||0)),connected:true,guesses:0,correct:0,points:0,xpEarned:0,penalty:0,riskTotal:0,riskGuesses:0}}
function resetStats(r){r.players.forEach(p=>Object.assign(p,{guesses:0,correct:0,points:0,xpEarned:0,penalty:0,riskTotal:0,riskGuesses:0}))}
function startDeathbox(r){r.gameId=randomId();r.startedAt=Date.now();r.started=true;r.naturalComplete=false;r.medalsAwarded=false;r.shuffleReady=false;r.round=0;r.turn=0;r.streak=0;r.selected=null;r.deck=shuffle(makeDeck());r.piles=Array.from({length:9},()=>[r.deck.pop()]);r.phase='outside';r.outsideCorrect=0;r.logs=[];r.result=`${r.players[0].name} goes first.`;resetStats(r)}
function startLethal(r){r.gameId=randomId();r.startedAt=Date.now();r.started=true;r.naturalComplete=false;r.medalsAwarded=false;r.shuffleReady=false;r.finalColorMode=false;r.finalTurnsRemaining=0;r.turn=0;r.streak=0;r.selected=null;r.deck=shuffle(makeDeck());r.piles=[[],[],[],[],[]];for(const i of[0,1,2,3,4])r.piles[i].push(r.deck.pop());r.phase='outside';r.outsideCorrect=0;r.logs=[];r.result=`${r.players[0].name} starts. Get two outside guesses, then the center color.`;resetStats(r)}
function start(r){r.game==='lethalcross'?startLethal(r):startDeathbox(r)}
function phaseLabel(r){if(r.game!=='lethalcross')return'';if(r.phase==='outside')return `${r.outsideCorrect}/2 outside`;if(r.phase==='center')return'Center color';if(r.phase==='finalColor')return `Final colors · ${r.deck.length} left`;return'Bonus center streak'}
function pub(r){return{code:r.code,gameId:r.gameId||null,hostId:r.hostId,started:r.started,naturalComplete:Boolean(r.naturalComplete),difficulty:r.difficulty,game:r.game,turn:r.turn,streak:r.streak,selected:r.selected,phase:r.phase,phaseLabel:phaseLabel(r),outsideCorrect:r.outsideCorrect||0,shuffleReady:Boolean(r.shuffleReady),round:r.round||0,finalColorMode:Boolean(r.finalColorMode),finalTurnsRemaining:r.finalTurnsRemaining||0,deckCount:r.deck.length,centerCount:r.game==='lethalcross'?(r.piles[2]?.length||0):0,piles:r.piles.map(p=>({count:p.length,top:p[p.length-1]||null})),players:r.players.map(p=>({id:p.id,name:p.name,badgeColor:badgeForLevel(xpProgress(p.xpTotal||0).level).color,badgeTier:badgeForLevel(xpProgress(p.xpTotal||0).level).tier,medals:p.medals||{easy:0,normal:0,hard:0},xp:xpProgress(p.xpTotal||0),connected:p.connected,guesses:p.guesses,correct:p.correct,points:p.points,xpEarned:p.xpEarned||0,penalty:p.penalty,riskTotal:p.riskTotal,riskGuesses:p.riskGuesses})),logs:r.logs.slice(0,120),result:r.result,timer:r.timer,reveal:r.reveal||null,currentPlayerId:r.players[r.turn]?.id||null}}
async function broadcast(r){await saveRoom(r);if(r.started||r.gameId)await snapshotRoom(r,r.started?'active':'completed');io.to(r.code).emit('roomState',pub(r))}async function socketRoom(s){return s.data.roomCode?getRoom(s.data.roomCode):null}function addLog(r,p,text,type='info'){r.logs.unshift({at:Date.now(),playerId:p?.id||null,player:p?.name||'',text,type})}function advance(r){r.turn=(r.turn+1)%r.players.length;r.streak=0;r.selected=null;r.phase='outside';r.outsideCorrect=0}function clearTimer(r){const h=timerHandles.get(r.code);if(h)clearInterval(h);timerHandles.delete(r.code);r.timer=null}
function chance(r,current,direction){if(!r.deck.length)return 0;return r.deck.filter(c=>direction==='higher'?c.value>current.value:c.value<current.value).length/r.deck.length}function riskPoints(x){return Math.max(1,Math.min(10,Math.round(1+(1-x)*9)))}function facePenalty(c){if(c.label==='A')return 11;if(['J','Q','K'].includes(c.label))return 10;return Number(c.label)}
const modeSeconds={easy:.4,normal:.8,hard:1.1};
function enterLethalFinal(r){
 if(r.finalColorMode)return;
 const outside=[0,1,3,4],pool=[...r.deck];
 for(const i of outside){pool.push(...r.piles[i]);r.piles[i]=[]}
 r.deck=shuffle(pool);r.finalColorMode=true;r.finalTurnsRemaining=r.deck.length;r.phase='finalColor';r.outsideCorrect=0;r.streak=0;r.selected=null;r.shuffleReady=false;
 r.result=`Final color round unlocked at 44 center cards. ${r.deck.length} color calls remain — one guess per player turn.`;
}
function recycleLethal(r){
 const outside=[0,1,3,4],pool=[];
 for(const i of outside){pool.push(...r.piles[i]);r.piles[i]=[]}
 r.deck=shuffle(pool);
 for(const i of outside)r.piles[i]=r.deck.length?[r.deck.pop()]:[];
 r.selected=null;r.shuffleReady=false;r.phase='outside';r.outsideCorrect=0;r.streak=0;
 r.result='The four outside piles were shuffled and redealt. The center pile stayed secured.';
}
function ensureLethalDeck(r){
 if(r.deck.length)return true;
 if(r.finalColorMode)return false;
 r.shuffleReady=true;r.result='All draw cards are dealt. Press Shuffle Cards to recycle the four outside piles.';return false
}
function setPenalty(r,p,seconds,nextTurn,reason){p.penalty+=seconds;const durationMs=Math.max(1,seconds)*modeSeconds[r.difficulty]*1000;r.timer={playerId:p.id,target:seconds,durationMs,startedAt:null,endAt:null,running:false,complete:false,nextTurn:Boolean(nextTurn),reason};r.streak=0;r.selected=null}
async function createRoom(host,s,difficulty,game){const code=await makeCode(),r={code,hostId:host.id,players:[host],difficulty:['easy','normal','hard'].includes(difficulty)?difficulty:'normal',game:game==='lethalcross'?'lethalcross':'deathbox',started:false,turn:0,streak:0,deck:[],piles:[],selected:null,phase:'outside',outsideCorrect:0,logs:[],result:'Waiting for the creator to start.',timer:null,lastActive:Date.now()};await saveRoom(r);await s.join(code);s.data.roomCode=code;s.data.playerId=host.id;return r}

function profileStats(p){const games=p.games||[];return games.reduce((a,g)=>{a.games++;a.guesses+=g.guesses||0;a.correct+=g.correct||0;a.penalty+=g.penalty||0;a.riskTotal+=g.riskTotal||0;a.riskGuesses+=g.riskGuesses||0;return a},{games:0,guesses:0,correct:0,penalty:0,riskTotal:0,riskGuesses:0})}
function profilePublic(p){normalizeSocial(p);const xp=xpProgress(p.xpTotal||0),badge=badgeForLevel(xp.level);return{token:p.token,username:p.username||'',name:p.name,badgeColor:badge.color,badgeTier:badge.tier,medals:p.medals||{easy:0,normal:0,hard:0},xp,activeRoomCode:p.activeRoomCode||null,games:(p.games||[]).slice(-40).reverse(),stats:profileStats(p),friends:p.friends,incomingRequests:p.incomingRequests,outgoingRequests:p.outgoingRequests}}
function publicProfile(p){if(!p)return null;return{username:p.username||'',name:p.name,badgeColor:badgeForLevel(xpProgress(p.xpTotal||0).level).color,badgeTier:badgeForLevel(xpProgress(p.xpTotal||0).level).tier,medals:p.medals||{easy:0,normal:0,hard:0},xp:xpProgress(p.xpTotal||0),stats:profileStats(p),createdAt:p.createdAt||null}}
async function upsertProfile(token,name){let p=await getProfile(token);if(!p)p={token:token||randomId(),username:'',name:clean(name),badgeColor:'#ff4055',medals:{easy:0,normal:0,hard:0},xpTotal:0,createdAt:Date.now(),games:[],activeRoomCode:null,friends:[],incomingRequests:[],outgoingRequests:[]};if(!p.medals)p.medals={easy:0,normal:0,hard:0};p.xpTotal=Math.max(0,Math.floor(Number(p.xpTotal)||0));p.badgeColor=badgeForLevel(xpProgress(p.xpTotal||0).level).color;if(name)p.name=clean(name)||p.name;await saveProfile(p);return p}
async function snapshotPlayer(r,pl,status='saved'){if(!pl?.profileToken)return;const pr=await getProfile(pl.profileToken);if(!pr)return;const rec={id:r.gameId||r.code,roomCode:r.code,game:r.game,difficulty:r.difficulty,status,medal:status==='completed'?r.difficulty:null,startedAt:r.startedAt||Date.now(),savedAt:Date.now(),guesses:pl.guesses||0,correct:pl.correct||0,xpEarned:pl.xpEarned||0,penalty:pl.penalty||0,riskTotal:pl.riskTotal||0,riskGuesses:pl.riskGuesses||0};const i=(pr.games||[]).findIndex(g=>g.id===rec.id);if(i>=0)pr.games[i]=rec;else(pr.games||(pr.games=[])).push(rec);pr.activeRoomCode=status==='active'?r.code:null;await saveProfile(pr)}
async function discardPlayerGame(r,pl){if(!pl?.profileToken)return;const pr=await getProfile(pl.profileToken);if(!pr)return;const gameId=r.gameId||r.code;pr.games=(pr.games||[]).filter(g=>g.id!==gameId);pr.xpTotal=Math.max(0,Math.floor(Number(pr.xpTotal)||0)-Math.max(0,Math.floor(Number(pl.xpEarned)||0)));if(pr.activeRoomCode===r.code)pr.activeRoomCode=null;await saveProfile(pr)}
async function snapshotRoom(r,status='active'){for(const pl of r.players)await snapshotPlayer(r,pl,status)}
async function completeNaturally(r,message){if(r.medalsAwarded)return;r.started=false;r.naturalComplete=true;r.medalsAwarded=true;r.shuffleReady=false;r.finishedAt=Date.now();r.result=message;for(const pl of r.players){if(pl.profileToken){const pr=await getProfile(pl.profileToken);if(pr){if(!pr.medals)pr.medals={easy:0,normal:0,hard:0};pr.medals[r.difficulty]=(pr.medals[r.difficulty]||0)+1;pl.medals={...pr.medals};await saveProfile(pr)}}}await snapshotRoom(r,'completed')}
function deathboxShuffle(r){const removeBy={9:3,6:2,4:3};const n=removeBy[r.piles.length];if(!n)return false;const indexed=r.piles.map((pile,i)=>({pile,i})).sort((a,b)=>b.pile.length-a.pile.length||a.i-b.i);const remove=new Set(indexed.slice(0,n).map(x=>x.i)),pool=[];r.piles.forEach((pile,i)=>{if(remove.has(i))pool.push(...pile)});r.piles=r.piles.filter((_,i)=>!remove.has(i));r.deck=shuffle(pool);r.round=(r.round||0)+1;r.shuffleReady=false;r.selected=null;r.streak=0;r.result=`Shuffle complete. ${r.piles.length} live piles remain.`;return true}


io.on('connection',s=>{
s.on('profileLogin',async({token}={})=>{try{const p=await getProfile(String(token||''));if(!p)return s.emit('authRequired');s.data.profileToken=p.token;s.emit('profileReady',profilePublic(p));if(p.activeRoomCode){const r=await getRoom(p.activeRoomCode);const pl=r?.players.find(x=>x.profileToken===p.token);if(r&&pl){pl.connected=true;pl.socketId=s.id;pl.name=p.name;pl.badgeColor=badgeForLevel(xpProgress(p.xpTotal||0).level).color;pl.medals={...(p.medals||{easy:0,normal:0,hard:0})};pl.xpTotal=Math.max(0,Math.floor(Number(p.xpTotal)||0));await s.join(r.code);s.data.roomCode=r.code;s.data.playerId=pl.id;s.emit('roomJoined',{playerId:pl.id,room:pub(r),resumed:true});await broadcast(r)}}}catch(e){s.emit('authRequired')}});
s.on('createAccount',async({username,passcode}={})=>{try{const u=cleanUsername(username);if(u.length<3)return s.emit('errorMessage','Username must be 3–18 characters using letters, numbers, or underscores.');if(!validPasscode(passcode))return s.emit('errorMessage','Passcode must be exactly 6 digits.');if(await getTokenByUsername(u))return s.emit('errorMessage','That username is already taken.');const token=randomId(),ph=hashPasscode(passcode),p={token,username:u,name:u,badgeColor:'#ff4055',medals:{easy:0,normal:0,hard:0},xpTotal:0,createdAt:Date.now(),games:[],activeRoomCode:null,friends:[],incomingRequests:[],outgoingRequests:[],passSalt:ph.salt,passHash:ph.hash};await saveProfile(p);s.data.profileToken=token;s.emit('profileReady',profilePublic(p))}catch(e){console.error(e);s.emit('errorMessage','Could not create the account.')}});
s.on('loginAccount',async({username,passcode}={})=>{try{const u=cleanUsername(username),p=await getProfileByUsername(u);if(!p||!validPasscode(passcode)||!verifyPasscode(passcode,p))return s.emit('errorMessage','Incorrect username or passcode.');s.data.profileToken=p.token;s.emit('profileReady',profilePublic(p));if(p.activeRoomCode){const r=await getRoom(p.activeRoomCode),pl=r?.players.find(x=>x.profileToken===p.token);if(r&&pl){pl.connected=true;pl.socketId=s.id;pl.name=p.name;pl.badgeColor=badgeForLevel(xpProgress(p.xpTotal||0).level).color;pl.xpTotal=p.xpTotal||0;await s.join(r.code);s.data.roomCode=r.code;s.data.playerId=pl.id;s.emit('roomJoined',{playerId:pl.id,room:pub(r),resumed:true});await broadcast(r)}}}catch(e){s.emit('errorMessage','Could not sign in.')}});
s.on('searchProfiles',async({query}={})=>{try{const u=cleanUsername(query),me=await getProfile(s.data.profileToken);if(!u)return s.emit('profileSearchResults',[]);const decorate=p=>{const row=publicProfile(p);if(!me)return{...row,relation:'none'};normalizeSocial(me);row.relation=p.username===me.username?'self':me.friends.includes(p.username)?'friend':me.incomingRequests.includes(p.username)?'incoming':me.outgoingRequests.includes(p.username)?'outgoing':'none';return row};const exact=await getProfileByUsername(u);if(exact)return s.emit('profileSearchResults',[decorate(exact)]);const found=[];if(!redis){for(const [name,token] of memoryUsernames){if(name.includes(u)){const p=await getProfile(token);if(p)found.push(decorate(p));if(found.length>=12)break}}}else{let cursor='0';do{const x=await redis.scan(cursor,{MATCH:`deathbox:username:*${u}*`,COUNT:100});cursor=String(x.cursor);for(const key of x.keys){const token=await redis.get(key),p=await getProfile(token);if(p)found.push(decorate(p));if(found.length>=12)break}}while(cursor!=='0'&&found.length<12)}s.emit('profileSearchResults',found)}catch(e){s.emit('profileSearchResults',[])}});
s.on('createRoom',async({name,difficulty,game,profileToken}={})=>{try{const n=clean(name);if(!n)return s.emit('errorMessage','Enter your name.');const token=profileToken||s.data.profileToken,pr=await getProfile(token),h=newPlayer(n,s.id,token,pr?.badgeColor,pr?.medals,pr?.xpTotal),r=await createRoom(h,s,difficulty,game);s.emit('roomJoined',{playerId:h.id,room:pub(r)});await broadcast(r)}catch(e){console.error(e);s.emit('errorMessage','Could not create the room.')}});
s.on('joinRoom',async({name,code:raw,profileToken}={})=>{try{const n=clean(name),code=norm(raw);if(!n)return s.emit('errorMessage','Enter your name.');const r=await getRoom(code);if(!r)return s.emit('errorMessage','That access code is not active.');const token=profileToken||s.data.profileToken,pr=await getProfile(token);const existing=r.players.find(x=>x.profileToken&&x.profileToken===token);if(existing){existing.connected=true;existing.socketId=s.id;existing.name=n;existing.badgeColor=badgeForLevel(xpProgress((pr?.xpTotal??existing.xpTotal) || 0).level).color;existing.xpTotal=Math.max(0,Math.floor(Number(pr?.xpTotal??existing.xpTotal)||0));await s.join(code);s.data.roomCode=code;s.data.playerId=existing.id;s.emit('roomJoined',{playerId:existing.id,room:pub(r),resumed:true});await broadcast(r);return}const p=newPlayer(n,s.id,token,pr?.badgeColor,pr?.medals,pr?.xpTotal);r.players.push(p);if(r.started){addLog(r,p,`${p.name} joined the game in progress.`,'info');r.result=`${p.name} joined the game and will enter the turn rotation.`}await s.join(code);s.data.roomCode=code;s.data.playerId=p.id;s.emit('roomJoined',{playerId:p.id,room:pub(r)});await broadcast(r)}catch(e){s.emit('errorMessage','Could not join the room.')}});
s.on('startGame',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r||p?.id!==r.hostId)return;if(r.game==='asshole'){if(r.players.length<4)return s.emit('errorMessage','Asshole requires at least 4 online players.');return s.emit('errorMessage','Online Asshole gameplay is not enabled in this build yet. Use Against AI for the playable test mode.');}start(r);await snapshotRoom(r,'active');await broadcast(r)});
s.on('selectPile',async index=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.started||!p||r.timer||r.reveal||r.players[r.turn]?.id!==p.id)return;const i=Number(index);if(!Number.isInteger(i)||!r.piles[i])return;if(r.game==='lethalcross'&&(r.phase!=='outside'||i===2))return;r.selected=i;await broadcast(r)});
s.on('choose',async direction=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.started||!p||r.timer||r.reveal||r.players[r.turn]?.id!==p.id||!['higher','lower'].includes(direction)||r.selected===null)return;if(!r.deck.length&&r.game==='lethalcross'&&!ensureLethalDeck(r)){await broadcast(r);return}if(!r.deck.length){r.shuffleReady=true;r.result='All cards in this round are dealt. Press Shuffle Cards.';await broadcast(r);return}const pile=r.piles[r.selected],cur=pile[pile.length-1],ch=chance(r,cur,direction),next=r.deck.pop();pile.push(next);const correct=direction==='higher'?next.value>cur.value:next.value<cur.value,aw=riskPoints(ch);p.guesses++;p.riskGuesses++;p.riskTotal+=aw;if(correct){p.correct++;const xpAward=await awardXP(r,p,aw);r.streak++;r.outsideCorrect=(r.outsideCorrect||0)+1;r.result=`${p.name} got ${direction} right on ${next.label}${next.suit}. +${xpAward.earned} XP${xpAward.leveled?` · LEVEL ${xpAward.level} ${xpAward.rank.toUpperCase()}!`:''} ${r.outsideCorrect}/2 outside guesses complete.`;addLog(r,p,r.result,'correct');r.selected=null;if(r.game==='lethalcross'&&r.outsideCorrect>=2){r.phase='center';r.result=`Two outside guesses complete. ${p.name} must now guess the center card color.`}else if(r.game!=='lethalcross'&&r.streak>=3){advance(r);r.result=`Turn complete. ${r.players[r.turn].name} is up.`}}else{const penalty=pile.length*(next.value===cur.value?2:1);r.result=`${p.name} missed. Drink for ${penalty} second${penalty===1?'':'s'} — the selected outside pile now has ${pile.length} cards.`;addLog(r,p,r.result,'wrong');r.reveal={playerId:p.id,card:next,message:r.result,penalty,nextTurn:false,reason:'outside',until:Date.now()+1800};r.phase='outside';r.outsideCorrect=0;setTimeout(async()=>{const x=await getRoom(r.code);if(!x?.reveal)return;const xp=x.players.find(z=>z.id===p.id);x.reveal=null;setPenalty(x,xp,penalty,false,'outside');await broadcast(x)},1800)}if(!r.deck.length&&r.game==='deathbox'){if(r.piles.length===1){await completeNaturally(r,'Deathbox complete — the final card reached the last pile!')}else{r.shuffleReady=true;r.result='Round complete. Press Shuffle Cards to remove the finished piles and continue.'}}await broadcast(r)});
s.on('chooseColor',async color=>{
 const r=await socketRoom(s),p=playerFor(r,s);
 if(!r?.started||r.game!=='lethalcross'||!p||r.timer||r.reveal||r.players[r.turn]?.id!==p.id||!['red','black'].includes(color)||r.phase==='outside')return;
 if(!r.deck.length){if(r.finalColorMode){await completeNaturally(r,'LethalCross complete — all 52 cards reached the center pile!')}else ensureLethalDeck(r);await broadcast(r);return}
 const wasFinal=Boolean(r.finalColorMode),next=r.deck.pop(),actual=['♥','♦'].includes(next.suit)?'red':'black';
 r.piles[2].push(next);p.guesses++;p.riskGuesses++;p.riskTotal+=5;
 const correct=color===actual;
 if(correct){
  p.correct++;const xpAward=await awardXP(r,p,5);r.streak++;
  r.result=`${p.name} called ${color.toUpperCase()} correctly: ${next.label}${next.suit}. +${xpAward.earned} XP${xpAward.leveled?` · LEVEL ${xpAward.level} ${xpAward.rank.toUpperCase()}!`:''}`;addLog(r,p,r.result,'correct');
  if(wasFinal){
   r.finalTurnsRemaining=r.deck.length;
   if(!r.deck.length)await completeNaturally(r,'LethalCross complete — all 52 cards reached the center pile!');
   else{advance(r);r.finalColorMode=true;r.phase='finalColor';r.result+=` ${r.players[r.turn].name} has the next color call. ${r.deck.length} cards remain.`}
  }else if(r.phase==='center'){r.phase='bonus';r.result+=' All three required guesses are complete — keep calling colors to build the center pile.'}
 }else if(wasFinal){
  const penalty=facePenalty(next);r.finalTurnsRemaining=r.deck.length;
  r.result=`${p.name} missed the final color call: ${next.label}${next.suit} was ${actual.toUpperCase()}. Drink for ${penalty}.`;addLog(r,p,r.result,'wrong');
  r.reveal={playerId:p.id,card:next,message:r.result,penalty,nextTurn:true,reason:'final-center',until:Date.now()+1800};
  setTimeout(async()=>{const x=await getRoom(r.code);if(!x?.reveal)return;const xp=x.players.find(z=>z.id===p.id);x.reveal=null;setPenalty(x,xp,penalty,true,'final-center');await broadcast(x)},1800);
 }else{
  const bonus=r.phase==='bonus';
  if(bonus){r.result=`${p.name} called ${color.toUpperCase()}, but ${next.label}${next.suit} was ${actual.toUpperCase()}. Bonus streak ended — no penalty.`;addLog(r,p,r.result,'wrong');advance(r);r.result+=` ${r.players[r.turn].name} is up.`}
  else{const penalty=facePenalty(next);r.result=`${p.name} called ${color.toUpperCase()}, but ${next.label}${next.suit} was ${actual.toUpperCase()}. Drink for ${penalty}.`;addLog(r,p,r.result,'wrong');r.reveal={playerId:p.id,card:next,message:r.result,penalty,nextTurn:false,reason:'center',until:Date.now()+1800};r.phase='outside';r.outsideCorrect=0;setTimeout(async()=>{const x=await getRoom(r.code);if(!x?.reveal)return;const xp=x.players.find(z=>z.id===p.id);x.reveal=null;setPenalty(x,xp,penalty,false,'center');await broadcast(x)},1800)}
 }
 if(!r.naturalComplete&&!r.finalColorMode&&(r.piles[2]?.length||0)>=44){
  enterLethalFinal(r);
  if(r.reveal){r.reveal.nextTurn=true;r.reveal.reason='final-center'}
 }
 if(!r.naturalComplete&&!r.finalColorMode&&!r.deck.length){r.shuffleReady=true;r.result+=' Press Shuffle Cards to recycle the outside piles.'}
 await broadcast(r)
});
s.on('startTimer',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.timer||r.timer.playerId!==p?.id||r.timer.running)return;r.timer.running=true;r.timer.startedAt=Date.now();r.timer.endAt=r.timer.startedAt+r.timer.durationMs;await broadcast(r);const h=setTimeout(async()=>{const x=await getRoom(r.code);if(!x?.timer)return;x.timer.complete=true;x.timer.running=false;await broadcast(x)},r.timer.durationMs);timerHandles.set(r.code,h)});
s.on('finishTimer',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.timer||r.timer.playerId!==p?.id||!r.timer.complete)return;const nextTurn=r.timer.nextTurn,reason=r.timer.reason;clearTimer(r);if(reason==='final-center'){r.finalTurnsRemaining=r.deck.length;if(!r.deck.length)await completeNaturally(r,'LethalCross complete — all 52 cards reached the center pile!');else{advance(r);r.finalColorMode=true;r.phase='finalColor';r.result=`Penalty complete. ${r.players[r.turn].name} has the next final color guess. ${r.deck.length} cards remain.`}}else if(nextTurn){advance(r);r.result=`Penalty complete. ${r.players[r.turn].name} is up.`}else{r.phase='outside';r.outsideCorrect=0;r.streak=0;r.selected=null;r.result=`Penalty complete. ${p.name} restarts the turn.`}await broadcast(r)});
s.on('shuffleCards',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r?.started||!p||!r.shuffleReady||r.timer||r.reveal)return;if(r.game==='deathbox'){if(!deathboxShuffle(r))return;if(r.piles.length===1&&r.deck.length===0)await completeNaturally(r,'Deathbox complete — one pile remains.')}else recycleLethal(r);addLog(r,p,`${p.name} shuffled the cards.`,'info');await broadcast(r)});

async function emitProfileToUsername(username){const p=await getProfileByUsername(username);if(!p)return;for(const sock of io.sockets.sockets.values()){if(sock.data.profileToken===p.token)sock.emit('profileReady',profilePublic(p))}}
async function friendSummaries(p){normalizeSocial(p);const rows=[];for(const username of p.friends){const fp=await getProfileByUsername(username);if(fp)rows.push(publicProfile(fp))}return rows.sort((a,b)=>(b.xp?.level||1)-(a.xp?.level||1)||(b.stats?.games||0)-(a.stats?.games||0))}

s.on('sendFriendRequest',async({username}={})=>{try{const me=await getProfile(s.data.profileToken),target=await getProfileByUsername(cleanUsername(username));if(!me||!target)return s.emit('errorMessage','Player not found.');normalizeSocial(me);normalizeSocial(target);if(me.username===target.username)return s.emit('errorMessage','You cannot friend yourself.');if(me.friends.includes(target.username))return s.emit('errorMessage','You are already friends.');if(me.incomingRequests.includes(target.username)){me.incomingRequests=me.incomingRequests.filter(x=>x!==target.username);target.outgoingRequests=target.outgoingRequests.filter(x=>x!==me.username);me.friends.push(target.username);target.friends.push(me.username);await saveProfile(me);await saveProfile(target);s.emit('profileReady',profilePublic(me));s.emit('friendsResults',await friendSummaries(me));await emitProfileToUsername(target.username);return}if(me.outgoingRequests.includes(target.username))return s.emit('errorMessage','Friend request already sent.');me.outgoingRequests.push(target.username);target.incomingRequests.push(me.username);await saveProfile(me);await saveProfile(target);s.emit('profileReady',profilePublic(me));await emitProfileToUsername(target.username)}catch(e){s.emit('errorMessage','Could not send friend request.')}});
s.on('acceptFriendRequest',async({username}={})=>{try{const me=await getProfile(s.data.profileToken),other=await getProfileByUsername(cleanUsername(username));if(!me||!other)return s.emit('errorMessage','Player not found.');normalizeSocial(me);normalizeSocial(other);if(!me.incomingRequests.includes(other.username))return s.emit('errorMessage','Friend request not found.');me.incomingRequests=me.incomingRequests.filter(x=>x!==other.username);other.outgoingRequests=other.outgoingRequests.filter(x=>x!==me.username);if(!me.friends.includes(other.username))me.friends.push(other.username);if(!other.friends.includes(me.username))other.friends.push(me.username);await saveProfile(me);await saveProfile(other);s.emit('profileReady',profilePublic(me));s.emit('friendsResults',await friendSummaries(me));await emitProfileToUsername(other.username)}catch(e){s.emit('errorMessage','Could not accept friend request.')}});
s.on('declineFriendRequest',async({username}={})=>{try{const me=await getProfile(s.data.profileToken),other=await getProfileByUsername(cleanUsername(username));if(!me)return;normalizeSocial(me);me.incomingRequests=me.incomingRequests.filter(x=>x!==cleanUsername(username));await saveProfile(me);if(other){normalizeSocial(other);other.outgoingRequests=other.outgoingRequests.filter(x=>x!==me.username);await saveProfile(other);await emitProfileToUsername(other.username)}s.emit('profileReady',profilePublic(me))}catch(e){s.emit('errorMessage','Could not decline request.')}});
s.on('removeFriend',async({username}={})=>{try{const me=await getProfile(s.data.profileToken),other=await getProfileByUsername(cleanUsername(username));if(!me)return;normalizeSocial(me);me.friends=me.friends.filter(x=>x!==cleanUsername(username));await saveProfile(me);if(other){normalizeSocial(other);other.friends=other.friends.filter(x=>x!==me.username);await saveProfile(other);await emitProfileToUsername(other.username)}s.emit('profileReady',profilePublic(me));s.emit('friendsResults',await friendSummaries(me))}catch(e){s.emit('errorMessage','Could not remove friend.')}});
s.on('getFriends',async()=>{try{const me=await getProfile(s.data.profileToken);s.emit('friendsResults',me?await friendSummaries(me):[])}catch(e){s.emit('friendsResults',[])}});
s.on('updateProfileName',async({name}={})=>{try{const n=clean(name),token=s.data.profileToken;if(!n||!token)return s.emit('errorMessage','Enter a valid name.');const pr=await getProfile(token);if(!pr)return s.emit('errorMessage','Profile not found.');pr.name=n;await saveProfile(pr);const r=await socketRoom(s),pl=playerFor(r,s);if(r&&pl){pl.name=n;await broadcast(r)}s.emit('profileReady',profilePublic(pr))}catch(e){s.emit('errorMessage','Could not update your name.')}});
s.on('getProfile',async()=>{const p=await getProfile(s.data.profileToken);if(p)s.emit('profileReady',profilePublic(p))});
s.on('saveAndFinish',async()=>{try{const r=await socketRoom(s),p=playerFor(r,s);if(!r||!p)return;if(p.id!==r.hostId)return s.emit('errorMessage','Only the room creator can finish the shared game.');clearTimer(r);r.reveal=null;r.started=false;r.finishedAt=Date.now();r.result='Game saved and finished by the creator.';addLog(r,p,r.result,'info');await snapshotRoom(r,'finished');const members=await io.in(r.code).fetchSockets();io.to(r.code).emit('gameFinished',{message:'Game saved and added to every player profile.'});for(const client of members){client.data.roomCode=null;client.data.playerId=null;await client.leave(r.code)}await deleteRoom(r.code)}catch(e){console.error(e);s.emit('errorMessage','Could not save and finish the game.')}});
s.on('quitAndCancel',async()=>{try{const r=await socketRoom(s),p=playerFor(r,s);if(!r||!p)return;if(p.id!==r.hostId)return s.emit('errorMessage','Only the room creator can cancel the shared game.');clearTimer(r);for(const pl of r.players)await discardPlayerGame(r,pl);const members=await io.in(r.code).fetchSockets();io.to(r.code).emit('gameFinished',{message:'Game canceled. All statistics and XP from this game were removed.'});for(const client of members){client.data.roomCode=null;client.data.playerId=null;await client.leave(r.code)}await deleteRoom(r.code)}catch(e){console.error(e);s.emit('errorMessage','Could not cancel the game.')}});
s.on('signOut',async()=>{try{s.data.profileToken=null;s.data.roomCode=null;s.data.playerId=null;s.emit('signedOut')}catch(e){s.emit('errorMessage','Could not sign out.')}});
s.on('newGame',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(!r||!p)return;await snapshotRoom(r,'archived');const pr=await getProfile(p.profileToken);if(pr){pr.activeRoomCode=null;await saveProfile(pr);s.emit('profileReady',profilePublic(pr))}s.leave(r.code);s.data.roomCode=null;s.data.playerId=null;s.emit('leftGame')});
s.on('restartGame',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(r&&p?.id===r.hostId){clearTimer(r);start(r);await broadcast(r)}});
s.on('disconnect',async()=>{const r=await socketRoom(s),p=playerFor(r,s);if(r&&p){p.connected=false;await broadcast(r)}})});
(async()=>{try{await initRedis();server.listen(PORT,HOST,()=>console.log(`Deathbox + LethalCross listening on ${PORT}`))}catch(e){console.error(e);process.exit(1)}})();
